extends: # Imports upstream linting rules
    - ./lint/eslintrc-gjs.yml
    - ./lint/eslintrc-shell.yml
parserOptions:
    sourceType: module
rules: # Override some of the upstream rules to match this codebase
    arrow-parens:
        - error
        - always
    curly:
        - error
        - all
    quotes:
        - error
        - double
    object-curly-spacing:
        - error
        - always
    no-unused-vars:
        - error
        - vars: all
          args: none
    indent:
        - error
        - 4
        - ignoredNodes:
              - "CallExpression[callee.object.name=GObject][callee.property.name=registerClass] > ClassExpression:first-child"
          MemberExpression: "off"
          SwitchCase: 1
    consistent-return: off
    no-await-in-loop: off
